---
chore:
  - changed-files:
      - any-glob-to-any-file:
          - ".editorconfig"
          - ".github/**/*.yml"
          - ".gitattributes"
          - ".gitignore"
          - ".golangci.yml"
          - ".goreleaser.yml"
          - "Makefile"
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "go.mod"
          - "go.sum"
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "examples/**/*"
          - "docs/**/*"
          - "docs-site/**/*"
          - "LICENSE"
          - "NOTICE"
github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**/*"
needs-review:
  - changed-files:
      - any-glob-to-any-file:
          - "**"
