// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package artifactory

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatartifactoryConfig is an auto-generated flat version of artifactoryConfig.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatartifactoryConfig struct {
	URL                     *string           `mapstructure:"url" required:"true" cty:"url" hcl:"url"`
	APIKey                  *string           `mapstructure:"api_key" cty:"api_key" hcl:"api_key"`
	AccessToken             *string           `mapstructure:"access_token" cty:"access_token" hcl:"access_token"`
	Username                *string           `mapstructure:"username" cty:"username" hcl:"username"`
	Password                *string           `mapstructure:"password" cty:"password" hcl:"password"`
	Repository              *string           `mapstructure:"repository" required:"true" cty:"repository" hcl:"repository"`
	ArtifactName            *string           `mapstructure:"artifact_name" required:"true" cty:"artifact_name" hcl:"artifact_name"`
	ArtifactPath            *string           `mapstructure:"artifact_path" cty:"artifact_path" hcl:"artifact_path"`
	ArtifactPathProperties  *bool             `mapstructure:"artifact_path_properties" cty:"artifact_path_properties" hcl:"artifact_path_properties"`
	MaxRetries              *int              `mapstructure:"max_retries" cty:"max_retries" hcl:"max_retries"`
	TimeoutSeconds          *int              `mapstructure:"timeout_seconds" cty:"timeout_seconds" hcl:"timeout_seconds"`
	Overwrite               *bool             `mapstructure:"overwrite" cty:"overwrite" hcl:"overwrite"`
	Properties              map[string]string `mapstructure:"properties" cty:"properties" hcl:"properties"`
	AdditionalOvfExtensions []string          `mapstructure:"additional_ovf_extensions" cty:"additional_ovf_extensions" hcl:"additional_ovf_extensions"`
}

// FlatMapstructure returns a new FlatartifactoryConfig.
// FlatartifactoryConfig is an auto-generated flat version of artifactoryConfig.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*artifactoryConfig) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatartifactoryConfig)
}

// HCL2Spec returns the hcl spec of a artifactoryConfig.
// This spec is used by HCL to read the fields of artifactoryConfig.
// The decoded values from this spec will then be applied to a FlatartifactoryConfig.
func (*FlatartifactoryConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"url":                       &hcldec.AttrSpec{Name: "url", Type: cty.String, Required: false},
		"api_key":                   &hcldec.AttrSpec{Name: "api_key", Type: cty.String, Required: false},
		"access_token":              &hcldec.AttrSpec{Name: "access_token", Type: cty.String, Required: false},
		"username":                  &hcldec.AttrSpec{Name: "username", Type: cty.String, Required: false},
		"password":                  &hcldec.AttrSpec{Name: "password", Type: cty.String, Required: false},
		"repository":                &hcldec.AttrSpec{Name: "repository", Type: cty.String, Required: false},
		"artifact_name":             &hcldec.AttrSpec{Name: "artifact_name", Type: cty.String, Required: false},
		"artifact_path":             &hcldec.AttrSpec{Name: "artifact_path", Type: cty.String, Required: false},
		"artifact_path_properties":  &hcldec.AttrSpec{Name: "artifact_path_properties", Type: cty.Bool, Required: false},
		"max_retries":               &hcldec.AttrSpec{Name: "max_retries", Type: cty.Number, Required: false},
		"timeout_seconds":           &hcldec.AttrSpec{Name: "timeout_seconds", Type: cty.Number, Required: false},
		"overwrite":                 &hcldec.AttrSpec{Name: "overwrite", Type: cty.Bool, Required: false},
		"properties":                &hcldec.AttrSpec{Name: "properties", Type: cty.Map(cty.String), Required: false},
		"additional_ovf_extensions": &hcldec.AttrSpec{Name: "additional_ovf_extensions", Type: cty.List(cty.String), Required: false},
	}
	return s
}
